### ISSUE TITLE
RSS Subscribe Page

### ISSUE THREAD

**Issue by 3willows** [RyanBrewer317/ryanbrewer-dev#2]
For some reason you [RSS Subscribe l](https://ryanbrewer.dev/feed.rss) link returns a 404 page not found.

On my feedly account, the latest blog post displayed is [Getting Started with Category Theory](https://ryanbrewer.dev/posts/getting-started-category-theory), so maybe it is some changes after July 29, 2024.

**Comment by RyanBrewer317** [comment]
Hey thanks for catching that and telling me!! I just deployed the fix. 

It was a casualty of my migration to Arctic: I'd forgotten to update part of the build script.
